### ISSUE TITLE
The adopt function failed to create the symbolic link

### ISSUE THREAD

**Issue by ran-deh** [raforg/danectl#1]
Thank you for creating danectl - DNSSEC DANE implementation manager.

I came across one issue. The original certificate was generated with "reuse_key" mode. Therefore, the adopt function failed to create the symbolic link within /etc/letsencrypt/current folder when using the adopt function.
 
root@mail: danectl adopt mail.example.org
adopt mail.example.org: Already in reuse_key mode

**Comment by raforg** [comment]
Thanks for reporting that. It's funny, the things that seemed
like a good idea at the time. I think I wanted it to only proceed
if things looked very standard, so it would be less likely to break
an existing non-standard renewal configuration. But it doesn't make
a lot of sense. I've changed it. Please try the latest commit.

**Comment by ran-deh** [comment]
Thank you very much that resolved the issue.
