### ISSUE TITLE
`danectl check` requires `/etc/letsencrypt`

### ISSUE THREAD

**Issue by paulmenzel** [raforg/danectl#13]
Using current master, commit 072d390 (doc - Add WHAT IS DANE? section), and just wanting to check the TLSA records of a domain, it’s aborting due to missing `certbot`.

    $ ./danectl check molgen.mpg.de
    danectl: Failed to find /etc/letsencrypt (install certbot)

Is it possible to just use danectl for checking TLSA records?

**Comment by raforg** [comment]
Hi, Sorry but danectl implements DANE, and it can only check TLSA records for certificates that it is managing the DANE implementation for, and it manages the implementation by using certbot. It compares the TLSA records in the DNS against the certbot certificate lineages.

But luckily, there are tools that check TLSA records against the key to be found by connecting to the TLS server in question, which sounds like what you want. Search for "check tlsa". Some web interfaces that show up are:

    Check a DANE TLS Service
    https://www.huque.com/bin/danecheck
    DANE SMTP Validator
    https://dane.sys4.de/

For the command line or cron, I think that Viktor Dukhovni uses ldns (https://github.com/NLnetLabs/ldns) but I don't know exactly how to use that to validate TLSA records.

There is also a DANE Wiki that lists DANE-related software:

    https://github.com/baknu/DANE-for-SMTP/wiki

It mentions this which looks like it might be a good automatable DANE checker:

    https://github.com/PennockTech/smtpdane

**Comment by paulmenzel** [comment]
Thank you for the clarification of the project scope, and the helpful references.
