### ISSUE TITLE
danectl-0.7.1 certbot failed

### ISSUE THREAD

**Issue by ran-deh** [raforg/danectl#3]
Hello Raf,

Danectl-0.7.1 fails when generating a new certificate. 
danectl: new example.com: certbot failed

I also tried danectl-0.7 and it works just fine.

It was tested on a new install of Ubuntu 20.04.

Thank you,
Randy

**Comment by raforg** [comment]
Hi Randy,

Thanks for that. Stupid mistake. It should be fixed now. Please try again.

cheers,
raf

**Comment by ran-deh** [comment]
Hello Raf,

It works with the change you made to the danectl file. 

Thank you,

Randy
